### PR TITLE
Volume expansion

### PR DESCRIPTION
**Pull request by ddymko**
## Description
This has the Resizer capabilities...however there are issues with v2 API and how volumes are mounted to the underlying disk. A solution is being worked on to address these.

### Checklist:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Have you linted your code locally prior to submission?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by robcxyz** [comment]
@ddymko - Can I ask the status of this PR?

**Comment by ddymko** [comment]
@robcxyz 

This is one hold due to block storage expansion requiring a restart for it to take effect. This makes it quite a disruptive behavior - I spoke with the storage team to see if there is anyway we can have volume expansion not require the restart as that would be ideal.

**Comment by robcxyz** [comment]
@ddymko - Thank you for update.  In the meantime is there any suggested procedure to do an expansion?  I tried simply restarting the pod after manual modification to the volume and PV and got: 

`Expander.NodeExpand found CSI plugin kubernetes.io/cs i/block.csi.vultr.com to not support node expansion `

**Comment by ddymko** [comment]
@robcxyz there is no way to do it with the CSI at the moment. You will have to deploy a new block and migrate the data over to the new one.

I'll look into seeing if we can offer the csi volume expansion with the caveat a user will have to restart the nodes...not the best solution.

**Comment by fredriklindberg** [comment]
At least having the possibility to expand a volume, even with the requirement of cycling nodes, would be great.

**Pull request closed without merging**
